### ISSUE TITLE
cache db python binding -- path variable issue -- intersys module not found

### ISSUE THREAD

**Issue by emalcolmb** [intersystems-ru/CacheGitHubCI#4]
Good morning IS Team,

TGIF! I'm a happy Cache DB user. I'm reaching out though with questions & feedback to share.

I read the docs on Cache's Python binding. From what I can tell, I'm hitting a path variable snag that appears to be a common issue that many users are experiencing.  Would it be possible to provide more specific instruction? Perhaps more detailed documentation? Or a quick 2-3 min video demo post to Youtube?

I've read through all the docs on the python binding & I followed the instructions here (https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=GBPY_intro#GBPY_intro_quickstart):

---I've downloaded Cache (C:\InterSystems\TryCache\bin)

---My system meets the client requirements for the python binding (https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=GBPY_intro_install_requirements)

---My 64-bit windows environment & paths are setup to run Microsoft C/C++ with Visual Studio 2017. In addition my vcvars64.bat path is set to C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build

---I execute the setup3.py file in my C:\InterSystems\TryCache\dev\python directory. It runs and prompts me for the cache installation directory, in which I paste in C:/InterSystems/TryCache/bin. 

--I then run test.py and this is what I see in powershell. A message that seems to say python doesnt know anything about the intersys module.  Please advise.

![cache_error](https://user-images.githubusercontent.com/40445985/51738561-49d3e800-2044-11e9-85d5-32bf322951c8.png)

**Comment by adaptun** [comment]
@emalcolmb this repository -- CacheGitHubCI -- has nothing to do with Python.

Please ask this question on community.intersystems.com
